version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pw
      POSTGRES_DB: rust_crud_app_course_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  your_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DATABASE_URL: postgres://postgres_user:postgres_pw@postgres/rust_crud_app_course_management
      APP_ENV: DOCKER
    ports:
      - "8080:8080"

volumes:
  postgres_data:

